/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "secondary-container": "#dae4eb",
              "on-error": "#ffffff",
              "surface-tint": "#46607d",
              "tertiary-fixed-dim": "#4ae183",
              "on-tertiary-container": "#00a656",
              "secondary-fixed-dim": "#bec8cf",
              "outline": "#73777e",
              "inverse-surface": "#2f3131",
              "on-primary": "#ffffff",
              "error-container": "#ffdad6",
              "on-tertiary": "#ffffff",
              "on-primary-fixed-variant": "#2e4964",
              "outline-variant": "#c3c6ce",
              "on-tertiary-fixed-variant": "#005228",
              "surface": "#f9f9f9",
              "on-surface": "#1a1c1c",
              "primary-fixed-dim": "#aec9ea",
              "surface-bright": "#f9f9f9",
              "surface-container-highest": "#e2e2e2",
              "secondary-fixed": "#dae4eb",
              "on-background": "#1a1c1c",
              "on-error-container": "#93000a",
              "on-secondary-fixed-variant": "#3e484e",
              "tertiary-container": "#003115",
              "primary-container": "#0d2b45",
              "primary-fixed": "#d0e4ff",
              "surface-container-low": "#f3f3f4",
              "on-surface-variant": "#43474d",
              "on-tertiary-fixed": "#00210c",
              "background": "#f9f9f9",
              "secondary": "#566066",
              "primary": "#00162a",
              "inverse-on-surface": "#f0f1f1",
              "on-secondary-fixed": "#131d22",
              "on-primary-container": "#7893b2",
              "surface-container-high": "#e8e8e8",
              "tertiary-fixed": "#6bfe9c",
              "surface-container-lowest": "#ffffff",
              "error": "#ba1a1a",
              "surface-dim": "#dadada",
              "surface-container": "#eeeeee",
              "surface-variant": "#e2e2e2",
              "on-secondary-container": "#5c666c",
              "inverse-primary": "#aec9ea",
              "on-primary-fixed": "#001d35",
              "tertiary": "#001a08",
              "on-secondary": "#ffffff"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "margin-mobile": "16px",
              "margin-desktop": "48px",
              "container-max": "1440px",
              "margin-tablet": "32px",
              "base": "8px",
              "gutter": "24px"
      },
      "fontFamily": {
              "headline-md": ["Inter"],
              "body-md": ["Inter"],
              "label-lg": ["Inter"],
              "body-lg": ["Inter"],
              "headline-lg-mobile": ["Inter"],
              "headline-lg": ["Inter"],
              "label-sm": ["Inter"],
              "headline-sm": ["Inter"]
      },
      "fontSize": {
              "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "label-lg": ["14px", {"lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "600"}],
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
              "headline-lg-mobile": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
              "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
              "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.04em", "fontWeight": "500"}],
              "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
